analysis name: deepreconS6-fmd-mscoco_fmriprep_500voxel_bvlc_reference_caffenet_allunits_fastl2lir_alpha100

# fMRI data
training fmri:

  S6:
    - ./data/fmri/train/S6_ImageNetTraining.h5
    - ./data/fmri/train/S6_FMD.h5
    - ./data/fmri/train/S6_MSCOCO.h5
    

test fmri:

  S6:
    - ./data/fmri/test/S6_Illusion.h5



rois:
  VC:     ROI_VC = 1
  

rois voxel num:
  VC:    500
  

label key:
  stimulus_name


num_training_samples: [6000, 5000, 5000]

# DNN features
training feature dir:
  - ./data/stimulus_feature/train/ImageNetTraining_S6
  - ./data/stimulus_feature/train/FMD
  - ./data/stimulus_feature/train/MSCOCO
  

network:
  caffe/bvlc_reference_caffenet

layers:
  - fc6


# Feature decoders
feature decoder dir:
  ./results/feature-decoding/ImageNetTraining_FMD_MSCOCO/derivatives/feature_decoders

# Decoded features
decoded feature dir:
  ./results/feature-decoding/Illusion_avg_trials/derivatives/decoded_features


# Learning parameters
alpha: 100
chunk axis: 1

